### ISSUE TITLE
On zarzad.html subpage, font weight on the sidebar seems to be lower for some reason.

### ISSUE THREAD

**Issue by igrell** [KMPSUJ/SEMPpage#9]
![image](https://user-images.githubusercontent.com/93985679/226210741-e4d1260e-1991-4106-998a-2f45c4fb25f6.png)
![image](https://user-images.githubusercontent.com/93985679/226210756-cf9824ac-d3b3-4ca7-a1f7-3baf07532c07.png)

**Comment by falcotinnunculus** [comment]
it's because CSS class `sidebar-nav-item.active` defined [here](https://github.com/KMPSUJ/SEMPpage/blob/b42dc0d6996696008e6f053edce7ae2f3604f31d/_css/poole_hyde.css#L348-L350) is used only on index.html, what is written [here](https://github.com/KMPSUJ/SEMPpage/blob/b42dc0d6996696008e6f053edce7ae2f3604f31d/_layout/sidebar.html#L7-L15)
